# Лабораторная работа 1
# "Построение матрицы расстояний между случайными точками"

## Списки в Python

### Создание списков

Для работы со списками в Python не требуется особой библиотеки, что, конечно, радует. 
Для создания списка достаточно просто задать переменную для его хранения и присвоить ей содержимое списка, которое указывается в [].

Списки могут содержать как целые числа

In [1]:
listInt = [1,2,3,4,5]
print (listInt)

[1, 2, 3, 4, 5]


In [1]:
doub = [23.5,2.2,0.5]
print (doub)

[23.5, 2.2, 0.5]


rty

#### так и вещественные

In [2]:
listFloat = [1.5,2.4,3.8,4.1,5.9]
print (listFloat)

[1.5, 2.4, 3.8, 4.1, 5.9]


#### да и вообще любой тип данных

In [3]:
# список слов
listWords = ['Python','List']
print (listWords)

['Python', 'List']


In [4]:
# список булевых значений
listBool = [False, True, False]
print (listBool)

[False, True, False]


Также можно создать просто пустой список

In [5]:
listEmpty = []
print (listEmpty)

[]


### Операции со списками

Для добавление элемента в конец списка используется метод append()

In [8]:
listEmpty.append(3)
print (listEmpty)

[2, 3]


Когда нужно добавить много элементов в окнец списка используется метод extend(), хотя им можно добавлять и по 1 элементу

In [9]:
listEmpty.extend(listInt)
print (listEmpty)

[2, 3, 1, 2, 3, 4, 5]


Очистить список можно методом clear()

In [10]:
listEmpty.clear()
print (listEmpty)

[]


Больше информации по работе со спиками есть здесь https://www.ibm.com/developerworks/ru/library/l-python_part_3/

Списки универсальный инструмент в Python и их можно заполнять не только вручную, но и с помощью циклов.
Сделаем список целых чисел от 0 до 9. Диапазон чисел задается методом range()

In [12]:
listRange= [i for i in range(1,10)]
print (listRange)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
list5 = [5]*10
print (list5)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


А сейчас сделаем список четных чисел от 0 до 9

In [2]:
listOdd = [i for i in range(10) if i%2 == 0]
print (listOdd)

[0, 2, 4, 6, 8]


In [5]:
listOddBul = [1 if i%2==0 else 0 for i in range(10)]
print (listOddBul)

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


##### Обращение к элементам списка

Чтобы обратиться к элементу списка нужно указаить имя списка и в [] номер элемента.
Обратимся к 0 элементу списка listOdd

In [16]:
print (listOdd[1])

2


А теперь к последнему

In [3]:
print (listOdd[-1])

8


Также можно обращаться к "кускам" списка

In [19]:
print (listOdd[1:5])

[2, 4, 6, 8]


## Массивы в Python

Работа с массивами в Python организована в библиотеке Numpy. Для начала ее нужно импортировать в проект. Сделаем это и сохраним библиотеку под коротким именем np

In [4]:
import numpy as np

### Создание векторов

Самый простой способ создать вектор в `NumPy` — задать его явно с помощью __`numpy.array(list, dtype=None, ...)`__.

Параметр __`list`__ задает итерируемый объект, из которого можно создать вектор. Например, в качестве этого параметра можно задать список чисел. Параметр __`dtype`__ задает тип значений вектора, например, __`float`__ — для вещественных значений и __`int`__ — для целочисленных. Если этот параметр не задан, то тип данных будет определен из типа элементов первого аргумента. 

In [21]:
vectorInt = np.array([1, 2, 3, 4])
print ('Вектор:\n', vectorInt)

Вектор:
 [1 2 3 4]


In [22]:
# или из готового списка
vectorIntList = np.array(listInt)
print (vectorIntList)

[1 2 3 4 5]


Другим способом задания вектора является функция numpy.arange(([start, ]stop, [step, ]...), которая задает последовательность чисел заданного типа из промежутка [start, stop) через шаг step:

In [23]:
vectorFloat = np.arange(start=0, stop=1, step=0.3, dtype=float)
print ('Вещественный вектор чисел от 0 до 1 с шагом 0.3:\n', vectorFloat)

Вещественный вектор чисел от 0 до 1 с шагом 0.3:
 [0.  0.3 0.6 0.9]


Можно создавать и вектора случайных чисел через метод np.random.sample(), где в качестве аргументов указывается количество случайных чисел

In [24]:
vectorRand = np.random.sample(10)
print (vectorRand)

[0.52034061 0.50481144 0.18064815 0.47036615 0.25780014 0.95642923
 0.58503704 0.84736387 0.92434981 0.57537199]


Подробнее про работу со случайными числами в Python и генераторы случайных чисел есть в http://librerussia.blogspot.com/2015/02/python-random.html

## Задание 1

На первом шаге создадим координаты X,Y случайных точек
Создайте 2 списка векторов случайных чисел X и Y. В каждом из них должны быть 3 вектора случайных чисел с 5, 10 и 30 случайными числами

In [5]:
X = [np.random.sample(5), np.random.sample(10), np.random.sample(30)]
Y = [np.random.sample(5), np.random.sample(10), np.random.sample(30)]
print("X = ", X)
print("Y = ", Y)

X =  [array([0.77876065, 0.50218487, 0.8985011 , 0.48188314, 0.61830089]), array([0.25145596, 0.16132354, 0.76602097, 0.51990289, 0.37440946,
       0.14748064, 0.12514024, 0.99174486, 0.48315246, 0.26716754]), array([0.72632074, 0.00929364, 0.5023766 , 0.24707429, 0.6084922 ,
       0.05211058, 0.82429514, 0.07180809, 0.87346377, 0.04747923,
       0.87485342, 0.75610725, 0.16003511, 0.33696864, 0.88685929,
       0.17268455, 0.35198022, 0.27177269, 0.45692445, 0.92695412,
       0.58091389, 0.43027836, 0.68034902, 0.46275768, 0.31479286,
       0.07917455, 0.03904427, 0.35548486, 0.16451444, 0.0600331 ])]
Y =  [array([0.06665997, 0.76512231, 0.90776157, 0.54306343, 0.32832426]), array([0.5710144 , 0.29002483, 0.04547463, 0.28508725, 0.90157994,
       0.20121988, 0.20704387, 0.74623276, 0.08479337, 0.34240076]), array([0.70976485, 0.72404667, 0.36712659, 0.57698508, 0.29194093,
       0.01618153, 0.8051811 , 0.94502556, 0.22240818, 0.00661719,
       0.47402387, 0.8418646 , 0.2274112

### Операции над векторами

Векторы в NumPy можно складывать, вычитать, умножать на число и умножать на другой вектор (покоординатно):

In [25]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])
k = 2

print ('Вектор a:', a)
print ('Вектор b:', b)
print ('Число k:', k)

Вектор a: [1 2 3]
Вектор b: [6 5 4]
Число k: 2


In [26]:
print ('Сумма a и b:\n', a + b)
print ('Разность a и b:\n', a - b)
print ('Покоординатное умножение a и b:\n', a * b)
print ('Умножение вектора на число (осуществляется покоординатно):\n', k * a)

Сумма a и b:
 [7 7 7]
Разность a и b:
 [-5 -3 -1]
Покоординатное умножение a и b:
 [ 6 10 12]
Умножение вектора на число (осуществляется покоординатно):
 [2 4 6]


### Нормы векторов

Вспомним некоторые нормы, которые можно ввести в пространстве  ℝn , и рассмотрим, с помощью каких библиотек и функций их можно вычислять в NumPy.

#### p-норма

p-норма (норма Гёльдера) для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
\left\Vert x \right\Vert_{p} = \left( \sum_{i=1}^n \left| x_{i} \right|^{p} \right)^{1 / p},~p \geq 1.
$$

В частных случаях при:
* $p = 1$ получаем $\ell_{1}$ норму
* $p = 2$ получаем $\ell_{2}$ норму

Далее нам понабится модуль `numpy.linalg`, реализующий некоторые приложения линейной алгебры. Для вычисления различных норм мы используем функцию __`numpy.linalg.norm(x, ord=None, ...)`__, где __`x`__ — исходный вектор, __`ord`__ — параметр, определяющий норму (мы рассмотрим два варианта его значений — 1 и 2). Импортируем эту функцию:

In [6]:
from numpy.linalg import norm

### $\ell_{1}$ норма

$\ell_{1}$ норма 
(также известная как [манхэттенское расстояние](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D1%85_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%B2))
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

Ей в функции __`numpy.linalg.norm(x, ord=None, ...)`__ соответствует параметр __`ord=1`__.

In [30]:
a = np.array([1, 2, -3])
print ('L1 норма вектора a:\n', norm(a, ord=1))

L1 норма вектора a:
 6.0


### $\ell_{2}$ норма

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

Ей в функции __`numpy.linalg.norm(x, ord=None, ...)`__ соответствует параметр __`ord=2`__.

In [31]:
print ('L2 норма вектора a:\n', norm(a, ord=2))

L2 норма вектора a:
 3.7416573867739413


### Расстояние между векторами

Для двух векторов $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ и $\ell_{2}$ раccтояния вычисляются по следующим формулам соответственно:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [32]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])
print ('L1 расстояние между векторами a и b:\n', norm(a - b, ord=1))

L1 расстояние между векторами a и b:
 17.0


In [33]:
print ('L2 расстояние между векторами a и b:\n', norm(a - b, ord=2))

L2 расстояние между векторами a и b:
 12.12435565298214


## Задание 2

Напишите функцию для расчета расстояния (как Евклидового, так и Манхэттенновского) между двумя точками, координаты которых, находятся в векторе Х и Y. Причем вектора содержат координаты не одной, а множества точек. Функция принимает на вход вектора с координатами Х и Y, а также переменную mode, указывающую режим расчета - Евклидово или Манхэттоновское расстояние. 
Функция возвращает список расстояний между точками.
Для расчета расстояния использовать метод norm

In [7]:
#Приведём списки векторов к просто векторам в соответствии с заданием "Функция принимает на вход вектора с координатами Х и Y"
X = [np.random.sample(5), np.random.sample(10), np.random.sample(30)]
Y = [np.random.sample(5), np.random.sample(10), np.random.sample(30)]

print("X = ", X)
print("Y = ", Y)

X =  [array([0.59440795, 0.29451908, 0.95931332, 0.24858365, 0.98551644]), array([0.9500079 , 0.33581438, 0.84999498, 0.02800532, 0.53832889,
       0.57459099, 0.30279342, 0.71689138, 0.30165111, 0.61451573]), array([0.77413763, 0.52556347, 0.50524715, 0.59625509, 0.14197474,
       0.25841652, 0.79000876, 0.63978976, 0.22029773, 0.08669548,
       0.01899087, 0.19401412, 0.01989319, 0.27131803, 0.47732371,
       0.50221806, 0.30124313, 0.61165754, 0.01449133, 0.9679577 ,
       0.76272141, 0.02613474, 0.41740205, 0.22141712, 0.47796433,
       0.97768809, 0.6447503 , 0.02914409, 0.11622933, 0.86650442])]
Y =  [array([0.68537819, 0.3571783 , 0.24919358, 0.81420659, 0.6778076 ]), array([0.60989698, 0.05163936, 0.30083896, 0.92023543, 0.84901165,
       0.68850085, 0.04077124, 0.02169   , 0.19410991, 0.50880557]), array([0.61934221, 0.67580429, 0.96629193, 0.54154083, 0.3769918 ,
       0.35144723, 0.93087979, 0.88386596, 0.7577339 , 0.76007138,
       0.25511713, 0.60424855, 0.7413182

In [8]:
def dist(X,Y,mode):
   #Создаём массив точек, где каждая точка - массив (то есть, массив массивов) 
    print("X =", X)
    print("Y =", Y)
    a = np.array([[X[i], Y[i]] for i in range(len(X))])
    print("a = \n", a)
    distances = []
    
    for i in range(0, len(a)):
        for j in range(0, len(a)):
            distance = norm(a[i] - a[j], ord=mode)
            distances.append(distance)
            print("L" + str(mode) + " расстояние между точками a[" + str(i) + "] и a[" + str(j) + "] равно " + str(distance))
            
        
    return distances

Примените полученную функцию. Сделайте список списков расстояний

In [10]:
distList = [dist(X[0], Y[0], 1)] # , dist(X[1], Y[1], 1), dist(X[2], Y[2], 1)]
print(distList)

X = [0.59440795 0.29451908 0.95931332 0.24858365 0.98551644]
Y = [0.68537819 0.3571783  0.24919358 0.81420659 0.6778076 ]
a = 
 [[0.59440795 0.68537819]
 [0.29451908 0.3571783 ]
 [0.95931332 0.24919358]
 [0.24858365 0.81420659]
 [0.98551644 0.6778076 ]]
L1 расстояние между точками a[0] и a[0] равно 0.0
L1 расстояние между точками a[0] и a[1] равно 0.6280887684315154
L1 расстояние между точками a[0] и a[2] равно 0.8010899847229763
L1 расстояние между точками a[0] и a[3] равно 0.47465269218158823
L1 расстояние между точками a[0] и a[4] равно 0.39867908354655623
L1 расстояние между точками a[1] и a[0] равно 0.6280887684315154
L1 расстояние между точками a[1] и a[1] равно 0.0
L1 расстояние между точками a[1] и a[2] равно 0.7727789625388812
L1 расстояние между точками a[1] и a[3] равно 0.5029637143656833
L1 расстояние между точками a[1] и a[4] равно 1.0116266701372545
L1 расстояние между точками a[2] и a[0] равно 0.8010899847229763
L1 расстояние между точками a[2] и a[1] равно 0.77277896253

### Создание матриц 

Приведем несколько способов создания матриц в NumPy.

Самый простой способ — с помощью функции numpy.array(list, dtype=None, ...).

В качестве первого аргумента ей надо передать итерируемый объект, элементами которого являются другие итерируемые объекты одинаковой длины и содержащие данные одинакового типа.

Второй аргумент является опциональным и определяет тип данных матрицы. Его можно не задавать, тогда тип данных будет определен из типа элементов первого аргумента. При задании этого параметра будет произведена попытка приведения типов.

Например, матрицу из списка списков целых чисел можно создать следующим образом:

In [323]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print ("Матрица:\n", a)

Матрица:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


Второй способ создания — с помощью встроенных функций numpy.eye(N, M=None, ...), numpy.zeros(shape, ...), numpy.ones(shape, ...).

Первая функция создает единичную матрицу размера  N×MN×M ; если  MM  не задан, то  M=NM=N .

Вторая и третья функции создают матрицы, состоящие целиком из нулей или единиц соответственно. В качестве первого аргумента необходимо задать размерность массива — кортеж целых чисел. В двумерном случае это набор из двух чисел: количество строк и столбцов матрицы.

#### Примеры:

In [4]:
ones = np.eye(5)
print ("Единичная матрица:\n", ones)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
zero = np.zeros((2,5))
print (zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
onlyOnes = np.ones((7, 5))
print ("Матрица, состоящая из одних единиц:\n", onlyOnes)

Матрица, состоящая из одних единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Обратите внимание: размерность массива задается не двумя аргументами функции, а одним — кортежем! Кортеж - набор чисел, заключенных в (). Поэтому помните о вторых () в аргументах!!!

И, наконец, третий способ — с помощью функции __`numpy.arange([start, ]stop, [step, ], ...)`__, которая создает одномерный массив последовательных чисел из промежутка __`[start, stop)`__ с заданным шагом __`step`__, и _метода_ __`array.reshape(shape)`__. 

Параметр __`shape`__, как и в предыдущем примере, задает размерность матрицы (кортеж чисел). Логика работы метода ясна из следующего примера:

In [309]:
v = np.arange(0, 24, 2)
print ("Вектор-столбец:\n", v)

Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [310]:
d = v.reshape((3, 4))
print ("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


#### Индексирование

In [317]:
print ("Второй элемент третьей строки матрицы:", d[2, 1])

Второй элемент третьей строки матрицы: 18


Из матрицы можно получать целые строки или столбцы с помощью выражений __`array[i, :]`__ или __`array[:, j]`__ соответственно:

In [37]:
print ("Вторая строка матрицы d:\n", d[1, :])
print ("Четвертый столбец матрицы d:\n", d[:, 3])

Вторая строка матрицы d:
 [ 8 10 12 14]
Четвертый столбец матрицы d:
 [ 6 14 22]


#### Транспонирование матриц

__Напоминание теории.__ __Транспонированной матрицей__ $A^{T}$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^{T}$ определяются как $a^{T}_{ij} = a_{ji}$, где $a^{T}_{ij}$ — элемент матрицы $A^{T}$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

В `NumPy` транспонированная матрица вычисляется с помощью функции __`numpy.transpose()`__ или с помощью _метода_ __`array.T`__, где __`array`__ — нужный двумерный массив.

In [32]:
a = np.array([[1, 2], [3, 4]])
aTransFun = np.transpose(a)
aTransT = a.T
print ('Матрица а: \n', a)
print ("Транспонирование функцией:\n", aTransFun)
print ("Транспонирование методом:\n",  aTransT)


Матрица а: 
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


#### Диагональная матрица

Диагональная матрица содержит элементы главной диагонали исходной матрицы.
Для получения диагональной матрицы из исходной используется метод np.diag(), параметром которого является исходная матрица

In [39]:
aDiag = np.diag(a)
print ('Диагональная матрица от а: \n', aDiag)

Диагональная матрица от а: 
 [1 4]


Если применить этот метод дважды к исходной матрице, то получим матрицу с 0 по всем элементам, кроме главной диагонали

In [40]:
aDiagDouble = np.diag(np.diag(a))
print (aDiagDouble)

[[1 0]
 [0 4]]


## Задание 3

Преобразите полученные списки расстояний в квадратные матрицы 

In [12]:
import math
def toSquareMatrix(Distances):
    l = len(Distances)
    n = int(math.sqrt(l))
    squareMatrix = np.zeros((n,n))
    z = 0
    #print(Distances)
    for i in range(0, n):
        for j in range(0, n):
            squareMatrix[i][j] = Distances[z]
            z = z+1                
    return squareMatrix

toSquareMatrix(distList[0])



array([[0.        , 0.62808877, 0.80108998, 0.47465269, 0.39867908],
       [0.62808877, 0.        , 0.77277896, 0.50296371, 1.01162667],
       [0.80108998, 0.77277896, 0.        , 1.27574268, 0.45481714],
       [0.47465269, 0.50296371, 1.27574268, 0.        , 0.87333178],
       [0.39867908, 1.01162667, 0.45481714, 0.87333178, 0.        ]])

## DataFrame

DataFrame являются удобным и общепринятым инструментом работы с датасетами. Для работы с ними нужна библиотека pandas. загрузим ее под кратким именем pd

In [14]:
import pandas as pd

### Создание DataFrame

DataFrame - это набор Series. Series - это вектор с заголовком. 

DataFrame можно создавать "вручную":

In [43]:
df = pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6]})
print (df)

   col1  col2
0     1     4
1     2     5
2     3     6


или из массивов

In [483]:
a = [[1,2], [4,5]]
dfArr = pd.DataFrame(a, columns = ['col1','col2'])
print (dfArr)

   col1  col2
0     1     2
1     4     5


Подробная информация по созданию DataFrame есть в документации pandas http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

#### Сохранение DataFrame в файл

DataFrame содержит ряд методов по сохранению в файл. Все они начинаются с to_
Сохраним полученный dataframe в excel

In [495]:
dfArr.to_excel('test.xlsx')

Файл запишется в папку проекта

## Задание 4

Создайте на основе полученного массива DataFrame и запишите его в файл excel

In [18]:
arr = toSquareMatrix(distList[0])
dfArray = pd.DataFrame(arr, columns = ['col1','col2','col3','col4','col5'])
print (dfArray)
dfArray.to_excel(r'C:\Users\1\Desktop\3 курс\Питон\'Test 1.xlsx')

       col1      col2      col3      col4      col5
0  0.000000  0.628089  0.801090  0.474653  0.398679
1  0.628089  0.000000  0.772779  0.502964  1.011627
2  0.801090  0.772779  0.000000  1.275743  0.454817
3  0.474653  0.502964  1.275743  0.000000  0.873332
4  0.398679  1.011627  0.454817  0.873332  0.000000


## Задание 5

Отсортируйте по возрастанию расстояния в DataFrame для любой из точек. Используйте метод DataFrame.sort_values()

In [21]:
dfArray = dfArray.sort_values(by=['col1'])
print(dfArray)

       col1      col2      col3      col4      col5
0  0.000000  0.628089  0.801090  0.474653  0.398679
4  0.398679  1.011627  0.454817  0.873332  0.000000
3  0.474653  0.502964  1.275743  0.000000  0.873332
1  0.628089  0.000000  0.772779  0.502964  1.011627
2  0.801090  0.772779  0.000000  1.275743  0.454817


## Запись в файл

Ниже приведена функцию записи списка значений в текстовый файл

In [32]:
def write_answer(listasn):
    with open("answer.txt", "w") as fout:
        fout.write(".".join([str(num) for num in listasn]))

Поробуйте разобраться в ней самостоятельно и используйте ее для записи списка точек в порядке возрастания расстояния между ними

In [35]:
write_answer(dfArray)
print(dfArray)

       col1      col2      col3      col4      col5
0  0.000000  0.628089  0.801090  0.474653  0.398679
4  0.398679  1.011627  0.454817  0.873332  0.000000
3  0.474653  0.502964  1.275743  0.000000  0.873332
1  0.628089  0.000000  0.772779  0.502964  1.011627
2  0.801090  0.772779  0.000000  1.275743  0.454817
